name: kodlite
description: A kotlin code editor project.

publish_to: 'none'

version: 1.0.0+2

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.2
  bloc_concurrency: ^0.2.0
  dartz: ^0.10.1
  rxdart: ^0.27.7
  path_provider: ^2.0.14
  get_it: ^7.2.0
  freezed_annotation: ^2.2.0
  riverpod: ^2.3.2
  flutter_riverpod: ^2.3.2
  process_run: ^0.12.5+2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  freezed: ^2.3.2
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
